name: Docker Build and Scan

on:
  workflow_dispatch:   # 👈 allows manual trigger from GitHub UI
  # push:              # (optional) you can keep/remove push trigger
  #   branches: [ main ]
  # pull_request:      # (optional) you can keep/remove PR trigger
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: 'my-app:latest'
          format: 'table'
          output: 'trivy-report.txt'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt
