name: CI with Trivy Scan

on:
  workflow_dispatch:   # 👈 Run manually from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=my-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      # 3️⃣ Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # 4️⃣ Scan Docker image
      - name: Run Trivy scan
        run: |
          mkdir -p trivy-reports
          trivy image --severity HIGH,CRITICAL --exit-code 0 --format table -o trivy-reports/report.txt $IMAGE_NAME

      # 5️⃣ Upload Trivy scan report
      - name: Upload Trivy report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: trivy-reports/