name: Trivy Scan Another Repo

on:
  workflow_dispatch:
    inputs:
      repo-to-scan:
        description: 'GitHub repo to scan (format: username/repo)'
        required: true
        default: 'myusername/other-repo'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout this repo (optional, for workflow context)
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      # 2️⃣ Checkout target repo to scan
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo-to-scan }}
          token: ${{ secrets.GH_PAT }}      # PAT required if repo is private
          path: target-repo                 # checkout to this folder

      # 3️⃣ Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # 4️⃣ Run Trivy scan on the target repo
      - name: Scan target repo with Trivy
        run: |
          mkdir -p trivy-reports
          trivy fs --severity HIGH,CRITICAL --exit-code 0 --format table -o trivy-reports/report.txt target-repo

      # 5️⃣ Upload scan report
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: trivy-reports/