name: Trivy Scan Repo & Docker Image

on:
  workflow_dispatch:
    inputs:
      repo-to-scan:
        description: 'GitHub repo to scan (format: username/repo)'
        required: true
        default: 'myusername/other-repo'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout workflow repo (optional)
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      # 2️⃣ Checkout target repo
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo-to-scan }}
          token: ${{ secrets.GH_PAT }}      # Required if private repo
          path: target-repo                 # Checked out to this folder

      # 3️⃣ Install Docker (for image build)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=my-app:${{ github.sha }}
          docker build -t $IMAGE_NAME target-repo
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      # 5️⃣ Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # 6️⃣ Scan repo (filesystem scan)
      - name: Trivy scan repository
        run: |
          mkdir -p trivy-reports
            # Scan the entire target repo folder (no Dockerfile required)
            trivy fs --severity HIGH,CRITICAL --exit-code 0 --format table -o trivy-reports/report.txt target-repo

      # 7️⃣ Scan Docker image
      - name: Trivy scan Docker image
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 0 --format json -o trivy-reports/image-scan.json $IMAGE_NAME

      # 8️⃣ Upload Trivy scan reports
      - name: Upload Trivy reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: trivy-reports/